plugins {
    id 'java-library'
}

dependencies {
    api project(':compat-api')
    compileOnly 'org.spigotmc:spigot-api:1.19.4-R0.1-SNAPSHOT'
}

def targetJavaVersion = 17
java {
    sourceCompatibility = JavaVersion.toVersion(targetJavaVersion)
    targetCompatibility = JavaVersion.toVersion(targetJavaVersion)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(targetJavaVersion)
}
